WZUI1 -> MY_MAGE_HELP_BTN_TIPTEXT
FSUI1 -> MY_MAGE_HELP_LV1_BTN_LIST
FSUI2 -> MY_MAGE_HELP_LV2_BTN_TP
FSUI3 -> MY_MAGE_HELP_LV2_BTN_TP_DOOR
FSUI4 -> MY_MAGE_HELP_LV2_BTN_BUFF
FSUI5 -> MY_MAGE_HELP_LV2_BTN_FOOD
FSUI6 -> MY_MAGE_HELP_LV2_BTN_ENGINEERING
FSUI7 -> MY_MAGE_HELP_LV2_BTN_JEWEL
